---
title: "setup"
author: "Vinita Vader"
date: "3/29/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(datadrivencv)
# Make a temp directory for placing files
# This would be a real location for a typical situation
temp_dir <- fs::dir_create(fs::path(tempdir(), "my_cv"))

use_datadriven_cv(
  full_name = "Vinita Vader",
   data_location = 
    #"https://docs.google.com/spreadsheets/d/14MQICF2F8-vf8CKPF1m4lyGKO6_thG-4aSwat1e2TWc",
  "https://docs.google.com/spreadsheets/d/1tF0cv68f4FHshLLOiDItlCtrtaY1cRXv0TLJrhmDmrk",
  pdf_location = "https://github.com/vvader24/cv/raw/master/vader_cv.pdf",
  html_location = "vvader.me/cv/",
  source_location = "https://github.com/vvader24/cv",
  #output_dir = temp_dir,
  open_files = FALSE
)

# Files should be where they were requested
list.files(temp_dir)#> [1] "cv_printing_functions.r" "cv.rmd"                 
#> [3] "dd_cv.css"               "render_cv.r"            

```

```{r}
# Knit the HTML version
rmarkdown::render("cv.rmd",
                  params = list(pdf_mode = FALSE),
                  output_file = "cv.html")

# Knit the PDF version to temporary html location
tmp_html_cv_loc <- fs::file_temp(ext = ".html")
rmarkdown::render("cv.rmd",
                  params = list(pdf_mode = TRUE),
                  output_file = tmp_html_cv_loc)

# Convert to PDF using Pagedown
pagedown::chrome_print(input = tmp_html_cv_loc,
                       output = "cv.pdf")
```

