---
title: "Vinita Vader's resume"
author: Vinita Vader
date: "`r Sys.Date()`"
output:
  pagedown::html_resume
    # set it to true for a self-contained HTML page but it'll take longer to render
    #self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================



Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> vvader@uoregon.edu
- <i class="fa fa-github"></i> [github.com/vvader24](https://github.com/vvader24)
- <i class="fa fa-phone"></i> +1 657-252-7501
- For more information, please contact me via email.


Statistical Areas of Expertise {#statsareas}
--------------------------------------------------------------------------------

- Machine Learning (Regression analysis, Principal Component analysis, Factor analysis, Network analysis, Cluster analysis)

- Data Visualization

- Advanced skills in R 

- Intermediate skills in Python, SQL



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown).

Last updated on `r Sys.Date()`.



Main
================================================================================

Vinita Vader {#title}
--------------------------------------------------------------------------------

### Research statement

I am currently a PhD student in Personality Psychology at University of Oregon. The theoretical premise for my research is that the study of _Culture_ underlies the study of _Personality_ and _Values_. I am interested in using machine learning techniques to build psychological mappings of people across societies and design a quantifiable model of culture. Psychometrics, building culture specific ( _emic_ ) surveys, and applying quantitative methods to design methods for psychological data sets. 


Relevant experince{data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------


###  Doctoral Researcher 

University of Oregon

Eugene, OR

2019 - Current

- MS thesis: High Dimensionality structure of English Language Type-nouns 
- Educational Data Science Specialization: Projects designed and executed include [World Value Survey](https://vvader24.github.io/EDLD2_FinalProject/),[Tutorial on functional programming](https://shijing-z.github.io/EDLD653-Final-Project/), [Hate Speech detection](https://github.com/vvader24/Hate-Speech-Project/blob/master/scripts/index.Rmd) 
- Research 
  -  "Lexical study of Personality and Values of Hindi Language speakers" - Developing a comprehensive dictionary of personality and value relevant words in Hindi and developing a measure for Hindi speakers
  - "High Dimensionality structure of Persian Language Adjectives" - Finding the most robust model for adjective structure in Persian language
  - "Culture relevant groupings using Values and Personality"  (Dissertation topic) - Developing a method to find cultural groups in a society based on thinking patterns. This project focuses on high dimensionality algorithms across cluster analysis, network analysis and PCA to understand the groups that can be formed 
- Teaching fellow 
  - Undergraduate courses: Research Methods (Sole instructor), Statistics (Lab instructor), Personality (Teaching assistant), Cultural Psychology (Teaching assistant) 
  - Graduate courses: [Statistics PSY 611 (Lab instructor)](https://uopsych.github.io/psy611/)
  - [R Bootcamp assistant (Summer 2021)](https://uopsych-r-bootcamp-2021.netlify.app/)

###  Teaching experience

University of Mumbai

Mumbai, India

2016 - 2018

- Graduate courses: Statistics for Psychology, Dissertation Guide, Psychological Testing and Psychometrics Practicals
- Undergraduate courses: Social Psychology, Counseling Psychology, Cognitive Psychology, Industrial Psychology, Experimental Psychology (Practicum and theory) 
  

###  Gradute level Researcher 

M.A. in Applied Psychology 

Mumbai, India

2014 - 2016



- Thesis: Working Memory Capacity in Caregivers of Alcoholics
- Clinial intern - Mental status examinations; Assessments - MMPI, MCMI, Kamat- Binet Test of Intelligence, VSMS, Seguin-Form Board, Children Apperception Test, Rorschach Ink Blot Test; Diagnosis (DSM-5, ICD 10)



Other Publications and Posters (selected){data-icon=file}
--------------------------------------------------------------------------------

### Factors affecting Academic Achievement in students : An empirical study - understanding the interaction between creativity, intelligence and academic achievement

Journal of Education and Planning. 2019; DOI: 10.13140/RG.2.2.32264.88328 

N/A

2019

**Vader**, Purohit, and Pandit. 

### What Lies at the Center of Rosenberg Self-Esteem Scale? Network Analysis and Latent Structure of Rosenberg Self-Esteem Scale for Indian Data

Bombay Psychologist. 2019.

N/A

2019 

Belhekar, **Vader**, Korgaonkar, and Dattakavi

### Note on [Iconic Sensory Memory](https://marathivishwakosh.org/45379/) and [Sensory Memory](https://marathivishwakosh.org/46655/)

for Marathi encyclopedia on Psychology Marathi Vishwakosh

N/A

2020 

**Vader**

### Acculturation and Personality among Indian students using the NEO-PI-3

Poster for 2020 American Psychological Association

USA

2019  

Heffern, **Vader**, Belhekar, Mellott


### Personality Structure in Marathi and English for Maharashtrians: A Psycholexical Investigation 

Paper presentation at Society for Cross Cultural Research Conference (SCCR) 2020
 
Seattle, USA
 
2020 

Belhekar and **Vader**

### MUFFI 2 – A culture sensitive measure of personality based on the Indian context 

Poster presentation at Society for Cross Cultural Research Conference (SCCR) 2020

Seattle, USA

2020

**Vader** and Belhekar

### The Five-Factor Model and Cultural dimensions in the Indian Context 

Poster presentation American Psychological Association (2019)

USA

2019

Heffern, **Vader**, Belhekar, Mellott

###	Using Factor analysis and Network analysis to delineate Personality Structure among Indian College Students

Poster presentation American Psychological Association (2018)

USA

2018

Heffern, **Vader**, Belhekar, Mellott

